7 erstellen der impressum kontakt page
dbalucas/wirwerkenmitholz pull request #33
Opened 2022-12-26 10:32 UTC by dbalucas

Using Formik and SendMailer module a new tool is built for handling the Formular

2023-02-09 18:28 UTC, HermannMarx requested changes

2023-02-09 18:28 UTC, HermannMarx commented on src/views/Kontakt/Kontakt.js
> +const initialValues = {
Bitte vorerst ohne Kontaktform, sondern einfach nur die Daten des Auftraggebers ;)

2023-02-12 14:46 UTC, dbalucas commented on src/views/Kontakt/Kontakt.js
> +const initialValues = {
alles rausgeworfen

2023-02-12 15:30 UTC, dbalucas reviewed
ok

2023-02-12 15:31 UTC, merged